name: Selenium Flask CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: flask_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest selenium psycopg2-binary

      - name: Start Flask App
        run: |
          export FLASK_APP=app.py
          nohup python -m flask run --host=0.0.0.0 --port=5000 &
          sleep 8  # wait for server to boot

      - name: Run Selenium Tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/flask_db
        run: |
          pytest testing/login_register_test.py --maxfail=1 --disable-warnings -q
